### ISSUE TITLE
Usage as default action for all jails

### ISSUE THREAD

**Issue by cantontowerstation** [enricotagliavini/fail2ban-digest#4]
Hi, just wondered if it's possible to use this as a default action for all jails, set in jail.local? If so, when I run the fail2ban-digest from cron (although I will probably use systemd) command, can I omit the 2nd arg? I am not sure what it does and I'm not good enough to work it out by looking through the code. I will hope to use this as I am also bothered by too many emails, unless you have any more up to date solution? Thank you

**Comment by enricotagliavini** [comment]
When you run ```fail2ban_digest maildigest secondarg``` the ```secondarg``` is the jail name as configured in fail2ban. This way you can have different digests for different jails. Most commonly this is used with the sshd jail, but you can make it the default for every jail you enable in fail2ban.

Then you should change your cron job to call ```fail2ban_digest maildigest``` once per every jail you configure to send out all the digest.

Does this help and answer your question?

Cheers!

**Comment by cantontowerstation** [comment]
Thanks for getting back to me. What I am trying to achieve is one digest for all my jails. I am still not entirely clear if this is possible. Perhaps I will give it another go though, with the info you have provided.

**Comment by enricotagliavini** [comment]
Oh yes this is possible. I would not recommend it because it's useful to know which jails are hit and when, but here it is: in the action you have this by default

```
actionban = /usr/local/bin/fail2ban_digest add <name> <ip>
```

If you change it to

```
actionban = /usr/local/bin/fail2ban_digest add all <ip>
```

all ips will be logged to the same database and one single digest can be produced

**Comment by cantontowerstation** [comment]
That's fantastic, thanks for the info (and for the code!). I'm hoping to get this set up this week. All the best.

**Comment by enricotagliavini** [comment]
you're welcome :)
